### PR TITLE
Remove deprecated `EmberError` and `assign`

### PR DESCRIPTION
**Pull request by wozny1989**
Task:
 - Remove deprecated `EmberError` - https://deprecations.emberjs.com/id/deprecate-ember-error
 - Remove deprecated `assign` - https://deprecations.emberjs.com/id/ember-polyfills-deprecate-assign

### CODE REVIEW

**Review by RobbieTheWagner — APPROVED** [review]

**Comment by dwickern** [comment]
@RobbieTheWagner could you make a release with this fix? It's a blocker for ember v5

**Comment by RobbieTheWagner** [comment]
@dwickern yes, apologies for the delay! I need to update this addon in general and setup release-plan so we can easily do releases in the future.

**Comment by RobbieTheWagner** [comment]
2.0.0 has been released, please let me know how it works for you!

**Comment by dwickern** [comment]
Works great!

I see now there's an [RFC to deprecate ember-fetch](https://github.com/emberjs/rfcs/pull/1065). If that happens, maybe this addon could drop the ember-fetch dependency and wire up the test waiters directly.

**Pull request merged**
